name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show Python info
        run: |
          python -V
          which python
          pip -V

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            echo "No requirements.txt found; continuing."
          fi
          if [ -f requirements-dev.txt ]; then
            python -m pip install -r requirements-dev.txt
          else
            echo "No requirements-dev.txt found; continuing."
          fi

      - name: Lint (ruff)
        run: |
          if [ -d src ] || [ -d tests ]; then
            ruff check src tests
          else
            echo "No src/ or tests/ directory; skipping ruff."
          fi

      - name: Format check (black)
        run: |
          if [ -d src ] || [ -d tests ]; then
            black --check src tests
          else
            echo "No src/ or tests/ directory; skipping black."
          fi

      - name: Run tests
        run: |
          if compgen -G "tests/*.py" > /dev/null; then
            pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=term-missing
          else
            echo "No tests found; skipping pytest."
          fi

      - name: Upload coverage artifact
        if: ${{ hashFiles('.coverage') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: ./.coverage